export default {
  anthropicKey: process.env.ANTHROPIC_API_KEY!,
  openaiApiKey: process.env.OPENAI_API_KEY || "",
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL || "http://localhost:11434",
  githubToken: process.env.GITHUB_TOKEN!,
  githubUsername: process.env.GITHUB_USERNAME!,
  githubClientId: process.env.GITHUB_CLIENT_ID!,
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET!,
  githubWebhookSecret: process.env.GITHUB_WEBHOOK_SECRET || "",
  jwtSecret: process.env.JWT_SECRET!,
  supabaseUrl: process.env.SUPABASE_URL!,
  supabaseServiceKey: process.env.SUPABASE_SERVICE_KEY!,
  stripeSecretKey: process.env.STRIPE_SECRET_KEY!,
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET!,
  stripeStarterPriceId: process.env.STRIPE_STARTER_PRICE_ID!,
  stripeProPriceId: process.env.STRIPE_PRO_PRICE_ID!,
  stripeProApiPriceId: process.env.STRIPE_PRO_API_PRICE_ID!,
  redisUrl: process.env.REDIS_URL || "redis://localhost:6379",
  adminSecret: process.env.ADMIN_SECRET!,
  cliVersion: process.env.CLI_VERSION || "1.0.0",
  runnerPollInterval: parseInt(process.env.RUNNER_POLL_INTERVAL_MS || "5000"),
  port: process.env.PORT || 3000,
  serverUrl: process.env.SERVER_URL || "http://localhost:3000",
}
